### ISSUE TITLE
Rajout : Contrôler le pc 

### ISSUE THREAD

**Issue by FazCodeFR** [Aymkdn/assistant-template#1]
Salut je suis un programmateur en vbs/batch et je suis très intéressé par ton projet
J'ai essayer de créé un plugin mais c'est la 1er fois que je touche a du js et node ... impossible de récupère la Commande reçue et de lancé un fichier batch

J'aimerais vraiment mettre la main a la pattes de ton projet, créé, participé 
Bref je m'explique : 
Rajouter un "Lance_XXXX" comme plugin qui lancerais un fichier bat qui aurais la fonction : 
Si Lance_Eteint alors eteindre le pc 
Si  Lance_Notepad alors lancé le notepad
Si Lance_Streaming alors lancé un film streaming sur la navigateur
Si Lance_CastPCtoTV alors caster le pc sur tv 
ect....

"Ok google, éteint l'ordinateur" -> Pushbullet -> node index.js qui reçoit Lance_Shutdows par exemple qui lance le fichier Lance.bat (qui contiendrais : si Lance_ variable égal Shutdows alors arrêté l’ordinateur) 

Les possibilité de la google home grandirais tellement ! 
"ok google, ouvre blocnote sur l'ordinateur" "cherche une mise a jour, défragmente, met un film Streaming et projette le sur la télévision"  etc.... ect.... 

J’espère que je t'ai convaincu
J’hésite pas a me contacter
mail : braunohler@gmail.com

Merci

**Comment by Aymkdn** [comment]
C'est en fait très simple à faire. Je te fais ça ces prochains jours si tu veux.

**Comment by Aymkdn** [comment]
Voilà, je viens de le coder ^^ Faut juste que je fasse quelques tests supplémentaires, et la doc !

Là je vais manger et me poser. J'essaie de regarder ça un peu demain.

**Comment by Aymkdn** [comment]
Et voilà : https://aymkdn.github.io/assistant-plugins/?plugin=launch

Le principe est de lancer un programme, en lui fournissant le chemin d'accès. Donc par exemple tu peux lui dire `OK Google, éteins le PC`, et tu crées un fichiers .bat avec la commande qui va bien. Ensuite, dans ton applet IFTTT, il suffit d'appeler ce .bat (par exemple *C:/MesBAT/eteint.bat*).

Tout est bien expliqué dans la doc (enfin, je pense). Si tu as des questions, demande moi.

**Comment by FazCodeFR** [comment]
Exacte tout est bien expliquer ! tu peux faire pour qu'il exécute n'importe quel fichier ? (.vbs .bat .rar .doc ect...) ?  Il semble que répondre pour les .exe
Merci !

**Comment by Aymkdn** [comment]
Normalement ça marche pour tous les fichiers exécutables (donc .bat .exe au moins)

Le .rar et .doc ne sont pas des exécutables. Il faudra indiquer l'application associée.

Par exemple `launch_"C:/Program Files/Microsoft Office/Office15/WINWORD.EXE" "C:/MonFichier.doc"`

**Comment by Aymkdn** [comment]
Je viens de tester un fichier .bat et ça a fonctionné.

Idem pour un fichier Word (avec le chemin indiqué ci-dessus).
